version: "3.9"
services:
  companies-service-app:
    container_name: companies-service-app
    build:
      context: ../
      target: ci
      dockerfile: dev/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - compose.dev.env
    depends_on:
      - companies-service-db
      - companies-service-migrate
      - companies-service-kafka
    volumes:
      - "..:/app"
    command: "go run main.go server"
    profiles:
      - app

  companies-service-db:
    container_name: companies-service-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=companies-service
      - POSTGRES_USER=companies-service
      - POSTGRES_DB=companies-service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U companies-service"]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - 6543:5432
    profiles:
      - app
      - dependencies

  companies-service-migrate:
    container_name: companies-service-migrate
    build:
      context: .
      dockerfile: migrations/Dockerfile
    env_file:
      - compose.dev.env
    depends_on:
      companies-service-db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - "../migrations:/migrations"
    profiles:
      - app
      - dependencies

  companies-service-kafka:
      container_name: companies-service-kafka
      image: bitnami/kafka
      ports:
          - "9092:9092"
      environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CREATE_TOPICS=companies_topic:1:1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BITNAMI_DEBUG=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      profiles:
        - app
        - dependencies
