// Code generated by mockery v2.10.6. DO NOT EDIT.

package auth

import mock "github.com/stretchr/testify/mock"

// MockIPDataProvider is an autogenerated mock type for the IPDataProvider type
type MockIPDataProvider struct {
	mock.Mock
}

// GetRequestLocation provides a mock function with given fields: ip
func (_m *MockIPDataProvider) GetRequestLocation(ip string) (string, error) {
	ret := _m.Called(ip)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
