// Code generated by mockery v2.10.6. DO NOT EDIT.

package auth

import mock "github.com/stretchr/testify/mock"

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

// IsActionAllowed provides a mock function with given fields: action, ip
func (_m *MockAuthService) IsActionAllowed(action Action, ip string) (bool, error) {
	ret := _m.Called(action, ip)

	var r0 bool
	if rf, ok := ret.Get(0).(func(Action, string) bool); ok {
		r0 = rf(action, ip)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Action, string) error); ok {
		r1 = rf(action, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
